@api = http://localhost:3000

####################################
##categoria
####################################

GET {{api}}/categorias
###
GET {{api}}/categoria/673c676056eda5d62933249d

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Electrónica",
    "descripcion": "Artículos de electrónica"
}

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Fitness",
    "descripcion": "Artículos de fitness"
}

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Indumentaria",
    "descripcion": "Artículos de indumentaria"
}

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Entretenimiento",
    "descripcion": "Artículos de entretenimiento"
}

####
PUT {{api}}/categorias/673c676056eda5d62933249d
Content-Type: application/json

{
    "nombre": "Fitness",
    "descripcion": "Artículos de fitne"
}

###
DELETE {{api}}/categorias/673c676056eda5d62933249d


