@api = http://localhost:3000


####################################
##items
####################################

GET {{api}}/items

###
GET {{api}}/item/673533410ce0faef596a420e

###
POST {{api}}/items
Content-Type: application/json

{
    "descripcion": "Smart TV",
    "categoria": "6733f85f234d9020b56fb775",
    "valor": 280000
}

###
POST {{api}}/items
Content-Type: application/json

{
    "descripcion": "Jogging",
    "categoria": "6733f86d234d9020b56fb778",
    "valor": 45500
}

###
POST {{api}}/items
Content-Type: application/json

{
    "descripcion": "Colchonetas",
    "categoria": "673c676056eda5d62933249d",
    "valor": 20000
}


###
PUT {{api}}/item/673c5d5b7af58e71a8f7d9d9
Content-Type: application/json

{
    "descripcion": "Kit Karaoke",
    "categoria": "6734eeb06809872e0848cb69",
    "valor": 1000
}

###
DELETE {{api}}/items/673c5d517af58e71a8f7d9d7

