@api = http://localhost:3000


####################################
##presupuestos
####################################

###
GET {{api}}/presupuestos

###
GET {{api}}/presupuesto/673ca5fdf9016c22eae2a599
### 
POST {{api}}/presupuesto
Content-Type: application/json

{
    "usuarioID": "673c8295cde02e82b9b30e31",
    "descripcion": "Presupuesto Marquitos",
    "montoLimite": 500000,
    "fechaInicio": "2025-1-01",
    "fechaFin": "2025-02-30",
    "alerta": true
}

###
PUT {{api}}/presupuesto/673c881dcde02e82b9b30e3a
Content-Type: application/json

{
    "usuarioID": "673c8295cde02e82b9b30e31",
    "descripcion": "Presupuesto editado",
    "montoLimite": 500000,
    "fechaInicio": "2025-1-01",
    "fechaFin": "2025-02-30",
    "alerta": true
}

###
DELETE {{api}}/presupuesto/673a5773f6bee58fba2cdf48
