@api = http://localhost:3000


####################################
##usuarios
####################################
GET {{api}}/usuarios

###
GET {{api}}/usuario/6734d0a9d281badbfda1cb2c

###
POST {{api}}/usuario
Content-Type: application/json

{
  "nombre": "karina",
  "email": "karina@email.com"
}

###
PUT {{api}}/usuario/6734d0a9d281badbfda1cb2c
Content-Type: application/json
    
{
  "nombre": "zara",
  "email": "cin@email.com.ar"
}

###
DELETE {{api}}/usuario/6734d0a9d281badbfda1cb2c


####################################
##costos
####################################
GET {{api}}/costos


###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "74999",
    "categoria": "6733f85f234d9020b56fb775"
}

###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "32.000",
    "categoria": "6733f870234d9020b56fb77a"
}


###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "17.879",
    "categoria": "6733f86d234d9020b56fb778"
}


###
DELETE {{api}}/costos/67329536ab265a8a6c25d9ca


####################################
##categoria
####################################

GET {{api}}/categorias

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Electrónica",
    "descripcion": "Artículos de electrónica"
}

###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Indumentaria",
    "descripcion": "Artículos de indumentaria"
}


###
POST {{api}}/categorias
Content-Type: application/json

{
    "nombre": "Entretenimiento",
    "descripcion": "Artículos de entretenimiento"
}


###
DELETE {{api}}/categorias/6732957a4b3ec8811973d52f

####

PUT {{api}}/categorias/67341774ee2c1eff76d8e4e4
Content-Type: application/json

{
    "nombre": "Entretenimientooooooo",
    "descripcion": "Artículos de entretenimiento"
}