@api = http://localhost:3000

GET {{api}}/costos

###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "74999",
    "categoria": "Electrónica"
}

###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "32.000",
    "categoria": "Entretenimiento"
}


###
POST {{api}}/costos
Content-Type: application/json

{
    "monto": "17.879",
    "categoria": "Indumentaria"
}


###
DELETE {{api}}/costos/673403b3604f4a38dbb40975