@api = http://localhost:3000


####################################
##usuarios
####################################

GET {{api}}/usuarios

###
GET {{api}}/usuario/673c8295cde02e82b9b30e31

###
POST {{api}}/usuario
Content-Type: application/json

{
  "nombre": "Marcos",
  "email": "markitos@email.com"
}

###
PUT {{api}}/usuario/6734dc002e3d03da338dc23f
Content-Type: application/json
    
{
  "nombre": "Zara",
  "email": "zaraa@email.com.ar"
}

###
DELETE {{api}}/usuario/6734dc002e3d03da338dc23f